### ISSUE TITLE
割り算ができない

### ISSUE THREAD

**Issue by ShuriIkeno** [pictomo/git-training-2023-06-16#2]
## 操作手順
* 〜したら
* 〜になった
割り算をしたら掛け算になった
## 本来の想定
* 〜したら
* 〜になってほしい
割り算にしたら、ちゃんと割り算にしてほしい
## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン
MacOS
googlechrome

**Comment by h-yki** [comment]
v1.2にて修正
